import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import { CsrfProvider } from '@/contexts/csrf-context';
import QueryProvider from '@/components/QueryProvider';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import LogoutButton from '@/components/LogoutButton';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <CsrfProvider>
            <SidebarProvider>
              <AppSidebar />
              <main className="flex-1 p-6 overflow-auto">
                <SidebarTrigger />
                <LogoutButton />
                {children}
              </main>
            </SidebarProvider>
          </CsrfProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
