import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReactNode } from 'react';
import { CsrfProvider } from '@/contexts/csrf-context';
import QueryProvider from '@/components/QueryProvider';
import ClientLayout from './ClientLayout';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <CsrfProvider>
            <ClientLayout>{children}</ClientLayout>
          </CsrfProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
